### ISSUE TITLE
Keychain Minder not appearing at screensaver lock

### ISSUE THREAD

**Issue by rtrouton** [google/macops#34]
I'm testing Keychain Minder on 10.9.5 and 10.10.5. I can get the Keychain Minder GUI to display when I click on a lock in System Preferences, but the GUI does not appear at the screensaver lock. 

When I checked `/var/log/install.log`, it appears that the auth db update did take place, as there's these two entries:

`postinstall: Mechanism installed`
`postinstall: Screensaver rule updated`

Is there anything I should be checking for?

**Comment by russellhancox** [comment]
If I recall correctly, the screensaver rule modification doesn't take effect until a reboot. Have you rebooted?

If it turns out that is the cause, I'll update the docs.

**Comment by rtrouton** [comment]
I've now rebooted, and it's still not appearing. When I dump system.login.screensaver to a plist, here's what I'm seeing:

https://gist.github.com/rtrouton/634577cc71a3ff49eeb5

**Comment by rtrouton** [comment]
I pulled that from my 10.10.5 test box. Mid 2014 13 inch MacBook Pro.

**Comment by russellhancox** [comment]
Ah, I see the issue now, the array to modify is called `rule` and the script is looking at `rules`. Pull request created.

**Comment by rtrouton** [comment]
I've tested the new rev and the screensaver lock is now working. Interestingly enough, a reboot is *not* required to make it work.

**Comment by russellhancox** [comment]
Thanks for the update. I'll remove the warning in the README
