### ISSUE TITLE
ValidateLoginPassword returning false positive

### ISSUE THREAD

**Issue by tburgin** [google/macops#35]
I am doing some tests with a local account. I found that after I reset the password with dscl, emulating a password change, ValidateLoginPassword function does not check the password properly. Anything I type into the password field will evaluate as true. This lets me reset my Keychain passwords to anything I desire. I have yet to test with a mobile account.

The logs below show that authd understands my password was invalid, but Keychain Minder continues on and resets my Keychain to the wrong password. Interesting.
```
Aug 17 15:14:07 MH02001208MACLT KeychainMinderGUI[1259]: KeychainMinder launched for admin
Aug 17 15:14:21 MH02001208MACLT authd[156]: engine[1259]: checkpw() returned -2; failed to authenticate user admin (uid 502).
Aug 17 15:14:21 MH02001208MACLT com.apple.xpc.launchd[1] (com.apple.imdmessageservices.IMDMessageServicesAgent): The _DirtyJetsamMemoryLimit key is not available on this platform.
Aug 17 15:14:21 MH02001208MACLT com.apple.xpc.launchd[1] (com.apple.imfoundation.IMRemoteURLConnectionAgent): The _DirtyJetsamMemoryLimit key is not available on this platform.
Aug 17 15:14:21 MH02001208MACLT authd[156]: engine[1259]: checkpw() returned -2; failed to authenticate user admin (uid 502).
Aug 17 15:14:21 MH02001208MACLT securityd_service[356]: resetting keybag for uid (502) in session (100005)
Aug 17 15:14:21 MH02001208MACLT kernel[0]: AppleKeyStore:Sending lock change 0 for handle 1
Aug 17 15:14:21 MH02001208MACLT kernel[0]: AppleKeyStore:Sending lock change 0 for handle -502
Aug 17 15:14:21 MH02001208MACLT kernel[0]: AppleKeyStore: operation failed (pid: 356 sel: 15 ret: e00002ce)
Aug 17 15:14:21 MH02001208MACLT KeychainMinderGUI[1259]: KeychainMinder Reset: 0
```

The logic of the ValidateLoginPassword and when it is called looks fine. However, I was able to get a false positive when fast user switching...

It doesn't look like you are using the `com.google.keychain-minder.validate-new-password` right for anything else. Any reason, besides the overhead, not to use the OD framework? `x` amount of incorrect password attempts will eventually lock out the user. I am not sure if `AuthorizationCopyRights` has that behavior or not...

``` Objective-C
BOOL ValidateLoginPassword(NSString *newPassword) {
    
    NSError *err = nil;
    ODSession *mySession = [ODSession defaultSession];
    ODNode *myNode = [ODNode nodeWithSession:mySession name:@"/Local/Default" error:&err];
    
    if (err) {
        NSLog(@"/Local/Default not found");
    }
    
    err = nil;
    ODRecord *myRecord = [myNode recordWithRecordType:kODRecordTypeUsers name:NSUserName() attributes:nil error:&err];
    
    if (err) {
        NSLog(@"%@ not found", NSUserName());
    }
    
    return [myRecord verifyPassword:newPassword error:nil];
    
}
```

Anyways, just some thoughts. I am impressed so far that no reboot is needed to reset local items! Yay!

**Comment by russellhancox** [comment]
Thanks for the report!

I'd copied that code from another project without realizing it only works if the user is an admin. I was worried about hard-coding /Local/Default in cases where the search path has something else first but there's an alternative I think I can use with nodeWithSession:type:error.

**Comment by tburgin** [comment]
So you would use `kODNodeTypeAuthentication` or `kODNodeTypeLocalNodes`?

If a user was a Network user with no mobile account, but does have a local home directory `kODNodeTypeLocalNodes` would not work, yes?

So either use `nodeWithSession:name:error:` and `/Search` 
or `nodeWithSession:type:error.` and `kODNodeTypeAuthentication`

I have never used `kODNodeTypeAuthentication`. Does it behave similarly to the `/Search` node?

**Comment by russellhancox** [comment]
I'm planning on using nodeWithSession:type:error with kODNodeTypeAuthentication. That seems to always return /Search but I prefer using the constant than hardcoding /Search myself.

**Comment by tburgin** [comment]
Nice! I have been hardcoding `/Search` for some other projects. I am going to look into migrating to `kODNodeTypeAuthentication`.

It is always beneficial chatting with you @russellhancox
