### ISSUE TITLE
Keychain Minder GUI appears after login, regardless of whether keychain password is correct or not.

### ISSUE THREAD

**Issue by rtrouton** [google/macops#40]
I've installed Keychain Minder 1.2, and I'm seeing that the Keychain Minder GUI now always appears after login. This may be due to the **RunAtLoad** flag being added to the LaunchAgent; removing it from the LaunchAgent addressed the behavior:

https://github.com/google/macops/commit/00d7ced672a559734a5bddf2a4d6b7bfe2f669f0#diff-6d8fc9394339d8e851330a157f0e13d3

**Comment by russellhancox** [comment]
Both this and #39 would make sense if you're running a debug build. The check for presence in the plist is skipped for Debug builds to make developing the UI easier.

**Comment by rtrouton** [comment]
OK. I'll build from the Xcode project again and see if that fixes it.

**Comment by rtrouton** [comment]
Dumb question: How do I build the Xcode project so that it's set for a release build rather than debug? It's  "Project: Build For: Running", correct?

**Comment by russellhancox** [comment]
No, Build For: Profiling. I'm removing the "ifdef DEBUG" line because it isn't that useful and is likely to lead to this problem.

**Comment by russellhancox** [comment]
This issue was moved to google/macops-keychainminder#3
