### ISSUE TITLE
Deprecation Notifier - overlays on additional screens do not close with click handler on 10.11 clients

### ISSUE THREAD

**Issue by andrewrosezen** [google/macops#50]
I built deprecation notifier to do some initial testing on my 10.11 computer, setting "expectedVersion" = "10.12" in Localizable.strings, and noticed that with multiple monitors, the mousedown event only successfully closes the overlay on the currently focused screen. Subsequent notifications seem to stack on the unfocused screen (translucency decreases), and the only way to close those is to kill the process itself.

**Comment by russellhancox** [comment]
I'm able to reproduce the first part (can only close by clicking on the currently focused screen) but not the second (subsequent notifications seem to stack).

There should not be any further notifications until the first one has been dismissed.

I believe the first part is fixed with #52.

**Comment by russellhancox** [comment]
#52 has been merged. Are you able to test again?

**Comment by andrewrosezen** [comment]
Works great, thanks for the head's up!
